### ISSUE TITLE
Add ability to deploy to site collection based app catalog

### ISSUE THREAD

**Issue by tom-daly** [rencoreab/vscode-spfx-deploy-package#1]
This would be even more awesome if we could target our site collection based app catalogs. 

Each one of our developers has sites that they deploy / test into with site collection based app catalogs. Having that feature would let us use this in that scenario.

**Comment by waldekmastykarz** [comment]
Thanks for the suggestion @tom-daly! It makes perfect sense and we'll definitely add it in the future versions of the extension.

**Comment by waldekmastykarz** [comment]
We've added support for this in v1.1.0 which we've just published. Looking forward to hear what you think!
