### ISSUE TITLE
Not able to install in MS Code v1.20

### ISSUE THREAD

**Issue by karthikeyantstad** [rencoreab/vscode-spfx-deploy-package#2]
PFA error Screenshot

Error MSG:

Unable to install 'RencoreGmbH.vscode-spfx-deploy-package'; there is no available version compatible with VS Code '1.20.0'.

![image](https://user-images.githubusercontent.com/40708557/45997701-1c8b2380-c0be-11e8-990d-18e3380b651f.png)

**Comment by waldekmastykarz** [comment]
Could you update VSCode to the latest version? It seems that your version is older than the version we used to build the extension.

**Comment by karthikeyantstad** [comment]
After VS Code upgrade. Its working.

Thank you

**Comment by waldekmastykarz** [comment]
Thank you for confirming it's working!
