### ISSUE TITLE
Add possibility to use extension without tenant admin rights

### ISSUE THREAD

**Issue by phawrylak** [rencoreab/vscode-spfx-deploy-package#3]
Currently you have to be Azure AD admin to grant permissions to the extension and be able to deploy package. It should be possible to use extension and deploy to site collection app catalog without Azure AD admin rights.

**Comment by waldekmastykarz** [comment]
You mean the permissions required to consent the Azure AD app when you use it the first time or the actual permissions when deploying the package to a site collection app catalog?

**Comment by phawrylak** [comment]
I mean permissions required to consent app in Azure AD.

**Comment by waldekmastykarz** [comment]
I don't think we have much choice here. The permission to manage site collection requires AAD-admin consent and AAD doesn't allow you to specify permissions for a single SharePoint site.

**Comment by phawrylak** [comment]
Maybe you could add possibility to use user credentials without Azure AD app registration? There is node-sp-auth library that should allow to do that easily.

**Comment by waldekmastykarz** [comment]
Unfortunately, it doesn't work if your account has MFA. Ideally, you should never enter your credentials in third party apps. This is why we chose to use OAuth instead of credentials.

**Comment by waldekmastykarz** [comment]
Closing due to lack of further reply
