### ISSUE TITLE
SPFx solution is not identified correctly

### ISSUE THREAD

**Issue by StfBauer** [rencoreab/vscode-spfx-deploy-package#4]
When I have multiple projects open and right click deploys solution I get to following error message.

Project Setup:
<img width="682" alt="screenshot 2018-10-08 at 09 12 56" src="https://user-images.githubusercontent.com/5503835/46596023-48a19e00-cadb-11e8-969d-0b876594cb1e.png">

A click on the root folder raise the following error message:
<img width="524" alt="screenshot 2018-10-08 at 09 19 01" src="https://user-images.githubusercontent.com/5503835/46596057-60792200-cadb-11e8-9770-9bb29c2804a8.png">
True because the angular project is just the first folder not the SPFx project

A click on the SPFx project cause the following error message:
<img width="542" alt="screenshot 2018-10-08 at 09 19 16" src="https://user-images.githubusercontent.com/5503835/46596080-7c7cc380-cadb-11e8-93ee-4e70bfed416d.png">
In this case it is a SPFx project but not identified as such.

**Comment by waldekmastykarz** [comment]
To deploy a package, you should select the .sppkg file, not the project. Unfortunately, VSCode doesn't support contextual menu items so we can't show the menu item only on .sppkg files.

**Comment by StfBauer** [comment]
Ouch. I was not aware that contextual is not supported and you also don't get on which path the user has clicked right.

**Comment by waldekmastykarz** [comment]
VSCode passes the path of the selected folder, but if there were multiple .sppkg files, would we have to deploy them all or show an error?

**Comment by StfBauer** [comment]
Multiple sppkg file in the same SPFx project? You can check the `.yo-rc.json`. Right now you only look at the first folder but when you check the `.yo-rc.json` yo can at least say.
"Found x solutions".

**Comment by waldekmastykarz** [comment]
What if the selected folder is not a project folder but a regular folder with multiple .sppkg files in it?

**Comment by StfBauer** [comment]
Then make a drop-down - All or individual - This will lead to "find all sppkg files" you over all directories but I guess you cannot create drop-downs.

**Comment by waldekmastykarz** [comment]
Unfortunately, not an option as far as I know

**Comment by waldekmastykarz** [comment]
Closing due to lack of further reply
