### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by agezez** [rencoreab/vscode-spfx-deploy-package#5]
Application was granted rights by a tenant admin and I can see "Connected" in VS Code.
I get an error eveery time i try to deploy. Why could that be ?
Error: RequestError: Error: self signed certificate in certificate chain

**Comment by waldekmastykarz** [comment]
Are you using a proxy or do you have Fiddler running by any chance?

**Comment by waldekmastykarz** [comment]
Closing due to lack of response.
